# Path to the CSV file
csv_path: "DEV-3023_dev_test.csv"

# API URL
api_url: "https://dev-api.dev.credoai.net/api/v2"

# API authentication token
auth_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9oR3ZvQURUVEM2OC1CMUJKRmtzXyJ9.eyJodHRwczovL2FwaS5jcmVkby5haS9yb2xlcyI6WyJhZG1pbiJdLCJodHRwczovL2FwaS5jcmVkby5haS90ZW5hbnQiOiJjcmVkb2FpIiwiaXNzIjoiaHR0cHM6Ly9jcmVkb2FpLWRldi51cy5hdXRoMC5jb20vIiwic3ViIjoib2lkY3xqdW1wY2xvdWQtcHJlcHJvZHw2NmZiMmRmZDI3YWU5YThkOGRjZGQxMmIiLCJhdWQiOlsiaHR0cHM6Ly9hcGkuY3JlZG8uYWkiLCJodHRwczovL2NyZWRvYWktZGV2LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3NDU1MjYxMjksImV4cCI6MTc0NTYxMjUyOSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBvZmZsaW5lX2FjY2VzcyIsIm9yZ19pZCI6Im9yZ19vR1VaajdHY1JMckhqRjdPIiwiYXpwIjoiTjExVFpxYVVFMnBrZFZFODlRYUw4dlhoUmZPNHNSSDAifQ.o52q3h1sbAR3NpeyGkeCpaDN7j_Rd9tHOpxcywqRuFiBIdckzsIE1-VMgr7fMjx0a01swiOIgmQE6uPjNZYkPDTHvNu6T4_6id8T8B_mt4AYdAGnuob5gW8dE9nHNDZNt1pW7rmcFH9x9yhAK_iOoFYzGrXuEppDXRki3eS_pTUog9x82GaZQZb0UQ6204NN-jeNu9IK0LreLXOOK3gHt_vDjZaoJc5RKS7i76xIT1sooOy8lnRMAa1fELzyCNLRJyBfimtPia2WxNmxqx4UjSJPFhNTKT3pZlJlxs01XA_3KdINih3qszPSzWNpv_0ywfkjP-GauUn8LwDqHeNlPg"

# Tenant identifier for the API
tenant: "credoai"

# Number of IDs (rows) to process. Leave empty or null to process all.
num_ids: 2

# List of custom field names to update
fields:
  - "DEV-3023"