# Path to the CSV file
csv_path: "DEV-3023_dev_test.csv"

# API URL
api_url: "https://dev-api.dev.credoai.net/api/v2"

# API authentication token
auth_token: "your_auth_token_here"

# Tenant identifier for the API
tenant: "credoai"

# Number of IDs (rows) to process. Leave empty or null to process all.
num_ids: 

# List of custom field names to update
custom_field_names:
  - "DEV-3023"