# Path to the CSV file
csv_path: "DEV-3023_dev_test.csv"

# Base URL
base_url: "https://dev-api.dev.credoai.net"

# API authentication token (read from environment variable)
api_token: "${CREDO_AI_API_TOKEN}"

# Tenant identifier for the API
tenant: "credoai"

# Number of IDs (rows) to process. Leave empty or null to process all.
num_ids: 

# List of custom field names to update
custom_field_names:
  - "DEV-3023"
  - "DEV-3023 A"