# Path to the CSV file
csv_path: "DEV-3023_dev_test.csv"

# API URL
api_url: "https://dev-api.dev.credoai.net/api/v2"

# API authentication token
auth_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Im9oR3ZvQURUVEM2OC1CMUJKRmtzXyJ9.eyJodHRwczovL2FwaS5jcmVkby5haS9yb2xlcyI6WyJhZG1pbiJdLCJodHRwczovL2FwaS5jcmVkby5haS90ZW5hbnQiOiJjcmVkb2FpIiwiaXNzIjoiaHR0cHM6Ly9jcmVkb2FpLWRldi51cy5hdXRoMC5jb20vIiwic3ViIjoib2lkY3xqdW1wY2xvdWQtcHJlcHJvZHw2NmZiMmRmZDI3YWU5YThkOGRjZGQxMmIiLCJhdWQiOlsiaHR0cHM6Ly9hcGkuY3JlZG8uYWkiLCJodHRwczovL2NyZWRvYWktZGV2LnVzLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE3NDU2MTE2ODksImV4cCI6MTc0NTY5ODA4OSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBvZmZsaW5lX2FjY2VzcyIsIm9yZ19pZCI6Im9yZ19vR1VaajdHY1JMckhqRjdPIiwiYXpwIjoiTjExVFpxYVVFMnBrZFZFODlRYUw4dlhoUmZPNHNSSDAifQ.F34UY5orOuUjLQJ34GLEJywyqHae19uP3hSYuOOHk-_zfIPYUF4s0dNYKGuMeqGkddT1OlAkYjyqU4El0jmIUcF7cn8WxDRtrr1GJowo1UMIv-mIxjGnefZozsFtTgbKBADephbwFS6y7_l-RNcsA09xnb9Lze3Lj9bobrVtWaUscRdCaa1blOFllorIDlZn085PBFaDKSPVzIKmePXlBkf7eW42yeNl82wPMFW0n2pTF4nykhWqFvkGFlV59M8c1bHvZWIy7-Sa352NtRSw40HRU90WUMV5PHXdlEr9LyuurL9NAXYJ8P-vhDFsY8SLO5XWJesNBjzJ2GithCcapQ"

# Tenant identifier for the API
tenant: "credoai"

# Number of IDs (rows) to process. Leave empty or null to process all.
num_ids: 

# List of custom field names to update
custom_field_names:
  - "DEV-3023"