# Path to the CSV file
csv_path: "data/dev-use-cases.csv"

# Base URL
base_url: "https://dev-api.dev.credoai.net"

# API authentication token
api_token: "your_api_token_here"

# Tenant identifier for the API
tenant: "credoaics"

# Number of IDs (rows) to process. Leave empty or null to process all.
num_ids: 2

# List of custom field names to update
custom_field_names:
  - "Business Type"